### ISSUE TITLE
Add syntax highlighting to Readme.md

### ISSUE THREAD

**Issue by Kyu** [chasefinch/data-enum#55]
Cool project, thank you for doing this. It is incredibly useful. 

In the readme, all the examples look bland, like for e.g

Minimal usage:

    from data_enum import DataEnum

    class Currency(DataEnum):
        data_attributes = ('symbol', 'name')

    Currency('CAD', symbol='$', name='Canadian dollar')
    Currency('USD', symbol='$', name='United States dollar')
    Currency('EUR', symbol='€', name='Euro')  

Using the github markdown code tags, specifically,
```md
\``` py
code_here
\``` 
```  

it could look like this  

```py

from data_enum import DataEnum

class Currency(DataEnum):
    data_attributes = ('symbol', 'name')

Currency('CAD', symbol='$', name='Canadian dollar')
Currency('USD', symbol='$', name='United States dollar')
Currency('EUR', symbol='€', name='Euro')
```  

Just a quick suggestion, it works for other languages too

**Comment by chasefinch** [comment]
Good idea. Feel free to submit a PR, or otherwise I'll make this update sometime this week.
